<?php 
/*  
$number1 =20;
$number2 =0;
if($number1 > $number2){
    echo "الرقم الاول اكبر";
    if($number1 === 20){
        echo "<br>";
        echo "الرقم الاول عشرون";
    }
}elseif($number1 < $number2){
    echo "الرقم الاول اصغر";
}
else{
    echo "الرقمين متساويين";
}*/

$username = "abdullah mohammed";
$email = "AZ@gmail.com";

if($username === "abdullah mohammed" && $email === "AZ@gmail.com"){
echo " Welcome Admin abdullah ";
}
?>